language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9-dev
script:
  - pip install -e ".[dev]"
  - invoke check
  - invoke test
after_success:
  - coveralls
deploy:
  provider: pypi
  username: __token__
  skip_existing: true
  password:
    secure: "iuX69tWVNbgKgclSZQ08my6sCyvDdEJAY6U/xcF9NK1X/TxDJmadwQAOUGpCs+gmEWs1wxZ+pI3HAmgS+89b47jToxmMbCo/lIndWbU2W3E+Dc8xa51r482OwcyJxXBwkoQCJRxKstwNkeHFVmww0KKPbyDwIC0u3+GxTLVvLd+u5PhNIQFGKrQMYkRPAOCNUfT8TLcJlXyUrTheahTimrD/wGKZc6iiubX4dUh9qNzCr1B9dlKc8zr4O0LlI2KsMKdDE3AtvyYy8J3oXmE5mVyxxbpx0wtHtF+QckBm96D5WIBMH8dz4r6JBlkYuofVF0lOFJeXf7kuB7B3C+X64YIoFUT7B0uv7g9aKGTREuQU3itnVhLPCVNE68zd8pG2fG55+3/mAVGUaLjCpFLoF9T4s7GZ03p4D6qj1DmrP8FyLPMkzhIoVuAcFS1sx4I7YopA+/AAXPTDb96WAGwEa1l2MhA1fVT+opL2eFpq2vYkADHSuw+ZUz8YxIBw4fAf+LM53beh2Gcirg2t/+6Jkuksv/2QC4nGRv0MnUi+ZObNB8VjrBIqdSO6KYc+KG1jGjPP5NYr5LIENftaUF5waoqis1o0aI3MItXUgisKf7fr42SJ6O//PBYWf8Kh0MY7vtrlJcDtZcGYah51iLlZFC6LOuEiVk3LcxLLnIWelao="
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: daviskirk/climatecontrol
