language: python
python:
  - 3.5
install:
  - pip install coveralls mypy-lang flake8
script:
  - flake8
  - python setup.py typecheck
  - python setup.py test
after_success:
  - coveralls
deploy:
  provider: pypi
  user: davis.kirkendall
  password:
    secure: "GqVHkynqp2aSG+qL3ix5xp9/7/LQvaZa6R+ze6p//MPDfbr1sMxMaRyRiM1xA5ZzE9UZsuwtrpP6vJ5WNzoaGmF6aIdMJj9Q5op9BSVrwsZJoUhCBOpi8rA6HnTpwNRHiQCILpldIAU8sy/M4zBgMXDzOyVPyOZ1tdCux32dRGplDNiHQ5Yxh9IF5bDqIACufHBK5FpkmuEMqnQLBwZHseCgL1pntwyfAoTy/Hgp2qG9v3ozXF1FEMju48K7CMjVsDxKoOVWbt0sS9rwoz3nqbR34aCdROJ+MplWDUvXmjI1iOOZWulCSUuk7D0bztNdGsjGGqhfwju6wjn14t0k6tY2d/C7xEM4BZtCwOTjdi/O7qYb7qDCwuohroVheDGZoumDTGk9wXS/6iwG3xYhEs75OJt+/o8dgU6V3ZNqTPuTtY9Uqy/PkUq6MtBPmfVrAOvFP2V4mhkBRi6tB7+lSSTF1eLiPz3ddkMENMm21KW/s/Q0wS/mcHnxx8TFeHsJiLmQagt2k6BRrHA+LbU2ZwstDsLP2lFRuHGB45Hb0s4xr7UBedU4x/8Z9Ql4RRerQcuhz12KRbs2Z+WbNVfpUZijyULrV35YyOqfBkpM9UBZjFqpeIBXc000wnsXjtzps1xh0TsW1gqJSFqKRFg57sD0omjCI50JHTSqKJQBOr0="
  on:
    tags: true
    branch: master
