name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: test (py${{ matrix.python-version }}, pydantic${{ matrix.pydantic-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        pydantic-version: ["1", "2"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install poetry
      uses: abatilo/actions-poetry@v3.0.0
      with:
        poetry-version: 1.8.3
    - name: Install dependencies
      run: |
        poetry install
    - name: Install Pydantic ${{ matrix.pydantic-version }}
      run: |
        if [ "${{ matrix.pydantic-version }}" = "1" ]; then
          poetry run pip install "pydantic>=1.9.0,<2.0"
        else
          poetry run pip install "pydantic>=2.0,<3.0"
        fi
    - name: Run checks and lint code
      run: |
        poetry run invoke check
    - name: Run tests
      run: |
        poetry run invoke test
        poetry run coverage xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
